### ISSUE TITLE
Client reconnect cleanup

### ISSUE THREAD

**Issue by UkoeHB** [lifescapegame/bevy_replicon#121]
The current replicon code does not clean up despawns/component removals on a client after the client reconnects, for despawns/removals that happened while the client was disconnected.

The client needs an additional `reconnect_system` which despawns all entities with `Replication` before the first call to `diff_receiving_system` after a client reconnects.

**Comment by Shatur** [comment]
I would be fine with any of the proposed solutions. On paper A sounds like easier for us, but harder for users. B sounds like harder for us, but better for users. So I would probably try to see how hard implementing B would end up.

**Comment by Shatur** [comment]
Quite a nice writeup!
This inspired me to another idea.

# Option 5: Treat reconnect as just a huge packet loss.

**On disconnect**

`bevy_replicon` server: move `ClientInfo` into a separate storage for some configurable time + additionally store the last sent tick from init message.
`bevy_replicon` client: Do nothing.
Game server: Clean up local entity trackers and do other custom logic to handle disconnects.
Game client: Run optional 'reinitializing' logic (e.g. display 'Reconnecting' message and block player inputs).

**On reconnect**

`bevy_replicon` client: include a special message that the client is trying to reconnect (if I recall correctly, Renet provides the ability to include user data into connection message).
`bevy_replicon` server: read the user message from the connected client and restore `ClientInfo`. Init messages will be send since the last received tick that we remembered. Update messages will be send as usual.

What do you think?

**Comment by Shatur** [comment]
> We don't have access to renet acks, so how do we know which replicon init message was last successfully sent?

Right, but what if we include it into user data when client tried to reconnect?

> What happens when ClientInfo times out?

I would expect it to just drop it. The configurable timeout is something after which in games you usually go into main menu with an error. So I would let users handle it.

> However it would give people the option to choose based on their use-case

Sure! And maybe the API for manual cleanup.

> We could do this:

Yes, this is how I would imagine it.

**Comment by Shatur** [comment]
> I.e. you won't disconnect a client that reconnects after ClientInfo is discarded, but you will discard them if they connect with a ClientInfo still present and fail to send 'I connected' in a timely manner?

No, no, the opposite:

- Client reconnected before the timeout - continue playing.
- Client reconnected after the timeout - disconnect, require users to write their logic to explicitly connect to the server from scratch.

> The client app should never completely break just because the server dropped ClientInfo. That is why I said "The client always uses Option 4.".

I think we are on the same page then.
What I suggesting is quite similar to Option 4, but solves the disadvantage of sending the big message.

**Comment by Shatur** [comment]
Oh, I get it now. I completely agree.

> The user data is fixed-length, it would not work.

Your suggestion with using reliable message also solves this problem, we can include any data into the "I reconnected" message.

**Comment by Shatur** [comment]
> Refactor pre-mapped entities: use ClientMapped and Premapped components,

But mappings should be processed first, before other data.

**Comment by Shatur** [comment]
After some thinking, I prefer not to provide any automation and let users handle this themselves by providing a label to register systems before retrieving the world.
Yes, the user will need to write restart logic, but that's what most games do, even single-player ones. It's not that hard, my game has it. The implementation of a feature to allow the user to have persistent entities is complex (4-5), and automatic despawn is too implicit (1-3).

So I would suggest that you first try to implement a reset in your game. If it turns out to be too difficult, discuss it again. It's easier to undo adding a label than a feature that complicates the library's internal logic. I would also prefer to have rooms if we decide to reiterate on it to see the whole picture.

Changing from "bug" to "enhancement".

**Comment by Shatur** [comment]
I like the proposed solution!
But let me think a bit more about pre-mapping, maybe we can somehow keep the current system. Not entirely sold on component-based API. If I don't come up with anything, then we will do as you suggested.
