### ISSUE TITLE
Support client predicted entities

### ISSUE THREAD

**Issue by RJ** [lifescapegame/bevy_replicon#67]
As part of migrating my custom netcode to replicon, i'm trying to sketch out how to handle client-predicted entities. 

Here's how I imagine it working with replicon:

* client presses shoot and immediately spawns a bullet with client entity of "CE".
* client sends shoot command to server, with a "hey, btw i spawned this entity already, with Entity = CE"
* server processes the client's shoot command, spawns the bullet with Entity = SE, and inserts to the `Res<ClientPredictedEntitiesMap>`, mapping {(SE, client_id) --> CE}
* when the server is building diffs, in server `collect_changes`, if the entity being written to the buffer 
is in the ClientPredictedEntitiesMap map, we include the predicted entity value in the buffer too ("CE").
* This is probably a case of writing an `Option<Entity>` to the ReplicationBuffer, and writing it after the `entity_data`.
 An Option<Entity> being a 1-bit cost if the predicted entity is None.
* in the client deserialize_component_diffs, we read the `Option<predicted_client_entity>`
* it's passed in to `let mut entity = entity_map.get_by_server_or_spawn(world, entity, predicted_client_entity);`
  and injected into the server_to_client map, to avoid spawning, if a predicted entity exists on the client.

That would allow clients to predict spawns and reconcile predicted entities with the server version.

Looking for a sanity check before I write more code.. sound sensible?

**Comment by Shatur** [comment]
I like it!
Initially I thought that we could send this information to a client via event, but if I understand correctly, it could be missed while the diff is received, so we need to send it as part of the diff.
But this raises a problem with events, what if an event contains an entity that client didn't receive? So maybe we should send events with the diff? This will solve the @RJ's problems (this one and the mentioned hack in discord with initial message as entity), the event mapping issue and allow us to use only a single channel instead of separate channel for each event.
@UkoeHB, @RJ what do you think?

**Comment by RJ** [comment]
Here's how i currently handle mispredicted spawns, and when they can occur:

Clients send an `InputCommands` packet to the server every frame, which includes inputs for the last N frames for some redundancy.

It's possible there's enough packet loss that an input for a frame where the client pressed shoot (and predicted a spawn) doesn't arrive at the server in time to be useful – or sometimes doesn't arrive at all.

When clients predict spawns, they insert a `PredictedSpawn {ttl: X}` component, where X is set to maximum number of frames it's reasonable for an input message to be in-flight for. (~150ms say)

When PredictedSpawn.ttl frames have elapsed on the client, the entity is immediately despawned by the client's misprediction system.

When spawn messages arrive from the server, with an attached client-predicted-entity that matches an existing entity (ie, everything is working as we hoped), the client removes the PredictedSpawn component.

In rare cases the client will despawn a bullet as a misprediction, and then very soon after the server spawn message for the bullet will arrive, with the client predicted entity attached (which has now been despawned). In this case, the client will notice the predicted entity doesn't exist, and spawn a new bullet. 

Perhaps this PredictedSpawn and cleanup system should also be part of replicon's client plugin?

(i will consider the concept of SyncEvents and respond later today!)

**Comment by RJ** [comment]
> The current events are directly piped to renet channels, which I think is a good feature (it gives you control over send policy and doesn't tie reliable events to replication throttling). 

I like how this works at the moment, and agree it's important to have access to tweak the channels as needed for each message.

However yes it doesn't help with the predicted spawn issue, because additional guarantees are needed to ensure the prediction data is available at spawn-time.

A new type of event, `SyncEvent` which is embedded in the replication stream (ie, written as part of the `ReplicationBuffer`) could solve the problem for now. Note that in my case, `SyncEvents` are always directed at just one client. But perhaps useful to be able to broadcast them too.

Let me describe the sequence of events to see if I understand what you're suggesting @UkoeHB –

## same scenario using SyncEvent

* client presses shoot and immediately spawns a bullet with client entity of "CE".
* client sends shoot command to server, with a "hey, btw i spawned this entity already, with Entity = CE"
* server processes the client's shoot command, spawns the bullet with Entity = SE, and issues a `SyncEvent`:
```rust
// runs on server
fn server_apply_input_commands(
  mut sync_events: EventWriter<ToClient<SyncEvent>>,
  mut commands: Commands,
  player_inputs: InputCommands,
) {
   if player_inputs.wants_to_shoot() && player_inputs.has_predicted_entity() {
    let server_entity = commands.spawn((Bullet{....}));
    sync_events.send(
        ToClient{ 
            client_id: player_inputs.client_id,
            event: SyncEvent::EntityRemap(player_inputs.predicted_entity(), server_entity)
         }
    );
    // ...
  }
}
```

Perhaps the sending API could potentially also be a new send `mode` for `ToClients`, which means add the event to the replication packets instead of the normal channels:

```rust
fn event_sending_system(mut dummy_events: EventWriter<ToClients<DummyEvent>>) {
    dummy_events.send(ToClients {
        mode: SendMode::SyncEvent(client_id),  // also support SendMode::SyncEventBroadcast ?
        event: DummyEvent,
    });
}
```

* when the server is building the `ReplicationBuffer` to send to a client, it includes any SyncEvents as described above.

### Considerations re: partial state updates

I'm trying to consider how this would work with partial state updates in the future too. ie, should we want to send individual single packets with diffs for a subset of entities. So I think we need to be able to lookup prediction data (or any sync-events) on a per entity basis when writing the diffs to the replicationbuffer.

In otherwords just collecting all syncevents this frame and writing to the top of the replicationbuffer perhaps isn't very futureproof. Feels like it should be within the per-entity section, at least for events like prediction, which are specific to an entity.

**Comment by RJ** [comment]
My previous issue discussed on discord about receiving the InitMessage before the replication stream is processed on the client would be solved by a SyncMessage directed at a single client, but not tied to an entity.

**Comment by Shatur** [comment]
> The current events are directly piped to renet channels, which I think is a good feature (it gives you control over send policy and doesn't tie reliable events to replication throttling).
> I like how this works at the moment, and agree it's important to have access to tweak the channels as needed for each message.

Good points.
But could it be dangerous to handle events on clients if its world state is different from the server's state at the time the event was emitted? This could cause bugs that are quite hard to find. Let's see if we can manage all use cases that "async" events can using "sync" events:

Since "sync" events are the part of the diff, they will be automatically part of specific room (see #15). This way, the user can group specific objects with specific events and be sure that the event will be handled correctly. For events that are totally independent of any world state (I think it's a rare case, but still), user can create a room without throttling for all such events.
Instead of `SendPolicy` I suggest to have the following two options for them:
- Overwritable. Any unacknowledged event will be overwritten with the new one.
- Reliable. Send until acknowledged or not. Is there a use case for it, btw?
`SendPolicy::ReliableUnordered` won't be needed since we have everything inside a single message.
Some events could be at the beginning of the snapshot (like mapping event), some events could be at the end. So this can be configurable too.

The idea is to make the "sync" behavior the default and allow users to explicitly configure which part of the world an event belongs to (or make it completely independent if the room contains no entities). Thoughts?

> Perhaps this PredictedSpawn and cleanup system should also be part of replicon's client plugin?

My initial plan for `bevy_replicon` was to have only replication and provide a flexible API to make rollback/prediction possible on top inside a separate crate to ensure modularity. Also my game, for example, need only replication, so I would like to maintain only this functionality.
This also one of the reasons why I suggested the concept of "sync" events instead of embedding prediction directly into diff.

But if having rollback/prediction separate will make the API complex, I'm happy to discuss implementing it as the part of the crate. But I will need someone responsible for this area, so you or someone else will need to join us in this case.
If we will figure the API for prediction/rollback in separate crate, I'm also fine with having something like `bevy_replicon_rollback` as part this repo if its author wants so (I imagine that it will be easier to maintain for him).

**Comment by Shatur** [comment]
> I'd like to avoid replicating any excess EntityRemap-related bits for users who don't need remapping

Agree with @UkoeHB here.
The suggestion above won't include any extra bits if not needed and can be used for spawning prediction case.

> If you send InitMessage as a SyncEvent, it is not necessary for that sync event to be ordered before the replication data in the replicon backend (if that's what you are suggesting)

You are right, sync event is not suited here. Probably should be solved with rooms as you suggested in Discord.

> I'm trying to consider how this would work with partial state updates in the future too.

Also forgot to answer this explicitly. Partial updates planned via rooms. So user group entities and events in rooms and we create separate diff for each room and ack them per room too.

**Comment by Shatur** [comment]
> Reliable. Send until acknowledged or not. Is there a use case for it, btw?
> Example: use events to transmit 'log events' of the game, which are recorded in an event-history panel.

Sorry, I probably phrased it wrong. I meant is there a use-case for **unreliable** events? The one we send only once and never acknowledge? Maybe just having "overwritable" option is enough?

> The big problem for me with eliminating normal renet event channels is you lose a path for sending large chunks of data efficiently.

Could you explain this use-case a bit more? Are you planning to send something large as part of initialization and want it to be separate from replication and don't want to send everything in a large message? If yes, shouldn't it be covered by rooms since we will send separate message for each room (or at least this is how I imagined it)?

If we decide to keep them, I would suggest to make "sync" events default (i.e. via `add_server_event`) and move current server events to `add_server_async_event`.

**Comment by Shatur** [comment]
> We https://github.com/lifescapegame/bevy_replicon/pull/21#issuecomment-1616087851 when we added send policy.

Now I remember why we added unreliable, thanks! Looks like I thought about this

> Like for fast-paced games with inputs as events.

I just think that "overwrite" option will work for this use case?

> I think what I am planning to do is beside the point.

Use cases are important. They dictates what library implements and what defaults will be. Having a less bug-prone API it's for the best. And I just trying to understand how async server events will be used. Not suggesting, just brainstorming.

Thinking about this events API more and it's probably won't work for the @RJ case because events processed **after** replication :(
We need to process them before. So while syncs events sounds good, maybe we should put them aside for another discussion. Mapping probably should be a special case, otherwise a new entity will be spawned on client before the spawn event will be processed. Or alternatively we could add custom spawn function + use it with the discussed sync event API?

**Comment by Shatur** [comment]
> It is fine to process them after.

For events - sure. But I think that @RJ need to update the predicted mappings before the replication? Otherwise server will just spawn a new entity instead of updating the predicted one.

**Comment by Shatur** [comment]
Since it a special case, do it without events at all?
Client insert entities to newly added field (let's call it `spawned_entities` (it could be used not only for predictions)) to `NetworkMap`. When sending ack, client sends now will send `ClientMessage` with tick and spawned entities. Server sends back array of mappings during the world diff. Client inserts mappings to `NetworkMap` before processing replicated entities.
Each message (client and server) will take 1 bit more. We could make a feature that disables it, but I think 1 extra bit is fine.
I think packing an optional entity for each entity will be less efficient, you don't do that much predictions.

**Comment by RJ** [comment]
i will do as simple of an initial implementation as i can to start, similar to how you describe. then we can figure out if it's worth making it more abstract 👍

**Comment by Shatur** [comment]
Good plan!
